development:
  amqp_uri: '<%= ENV.fetch("RABBITMQ_URL", "amqp://guest:guest@localhost:5672") %>'
  exchange: 'killjoy'
  exchange_type: 'x-modulus-hash'
  shards: <%= ENV.fetch("RMQ_SHARDS", 4).to_i %>
  heartbeat: 2
  prefetch: 8
test:
  amqp_uri: '<%= ENV.fetch("RABBITMQ_URL", "amqp://guest:guest@localhost:5672") %>'
  exchange: 'killjoy'
  exchange_type: 'x-modulus-hash'
  shards: <%= ENV.fetch("RMQ_SHARDS", 4).to_i %>
  heartbeat: 2
  prefetch: 8
production:
  amqp_uri: '<%= ENV.fetch("RABBITMQ_URL", "amqp://guest:guest@localhost:5672") %>'
  exchange: 'killjoy'
  exchange_type: 'x-modulus-hash'
  heartbeat: 2
  prefetch: 8
  shards: <%= ENV.fetch("RMQ_SHARDS", 4).to_i %>
