#!/usr/bin/env ruby

require "bundler/setup"
$LOAD_PATH.unshift(File.expand_path("../lib", File.dirname(__FILE__)))
require "killjoy"
require "killjoy/server"

configuration = Killjoy::AMQPConfiguration.new
server = ServerEngine::Daemon.new(Killjoy::Server, Killjoy::Worker, {}) do
  {
    daemonize: false,
    pid_path: 'tmp/killjoy.pid',
    queue_shards: configuration.shards,
    worker_type: 'process',
    workers: 1, # configuration.shards,
  }
end
server.run
