#!/usr/bin/env ruby

require "bundler/setup"
$LOAD_PATH << File.expand_path("../lib", File.dirname(__FILE__))
require "killjoy"
require "killjoy/experiments"
require "benchmark/ips"

if RUBY_PLATFORM == "java"
else
  require "stackprof"
end

experiments = Killjoy::Experiments.new(enable_profiler: false)
#experiments.non_blocking_writes

Benchmark.ips do |x|
  x.config(time: 5, warmup: 2)
  x.report("cassandra: blocking writes") do
    experiments.blocking_writes
  end
  x.report("cassandra:: non blocking writes") do
    experiments.non_blocking_writes
  end
  x.report("mongo: writes") do
    experiments.mongo_writes
  end
  x.report("kafka-mongo: writes") do
    experiments.kafka_mongo_writes
  end
  x.report("kafka-cassandra: non blocking writes") do
    experiments.kafka_cassandra_non_blocking_writes
  end

  x.compare!
end
