#!/usr/bin/env ruby

require "bundler/setup"
$LOAD_PATH << File.expand_path("../lib", File.dirname(__FILE__))
require "killjoy"

log_file = ENV.fetch("LOG_FILE", "spec/fixtures/nginx.log")
parser = Killjoy::LogParser.new
configuration = {
  amqp_uri: ENV.fetch("RABBITMQ_URL", "amqp://guest:guest@localhost:5672"),
  exchange: 'killjoy',
  exchange_type: 'x-modulus-hash',
  heartbeat: 2,
  prefetch: 8,
}

Killjoy::Publisher.using(configuration) do |publisher|
  log_file = File.join(Dir.pwd, log_file)
  lines = File.readlines(log_file)

  loop do
    lines.each do |line|
      publisher.publish(parser.parse(line))
    end
  end
end
