#!/usr/bin/env ruby

require "bundler/setup"
$LOAD_PATH.unshift(File.expand_path("../lib", File.dirname(__FILE__)))
require "killjoy"
require "killjoy/worker"
require "killjoy/server"
require "serverengine"

cpus = Facter.value('processors')['count'].to_i

#Sneakers.configure({
#threads: cpus,
#})

server = ServerEngine.create(Killjoy::Server, Killjoy::Worker) do
  {
    amqp_uri: ENV.fetch("RABBITMQ_URL", "amqp://guest:guest@localhost:5672"),
    daemonize: false,
    exchange: 'killjoy',
    exchange_type: 'x-modulus-hash',
    heartbeat: 2,
    pid_path: 'tmp/killjoy.pid',
    prefetch: cpus,
    queue_shards: ENV.fetch("RMQ_SHARDS", 4),
    run_asynchronously: ENV["ASYNC"] == 'true',
    worker_type: 'process',
    workers: ENV.fetch("RMQ_SHARDS", 4),
  }
end
server.run
